### ISSUE TITLE
This app download on apps.splunk is actually broken

### ISSUE THREAD

**Issue by koopertrooper** [splunk/splunk-ref-pas-code#16]
The archive doesn't contain any normal splunk file artifacts at all (ie. appserver/default/local/metadata etc).

Inside the pas_ref_app.tar file are :

dateutil
 - zoneinfo
- various python files.
EGG-INFO
 - dependency_links.txt
- not-zip-safe
- PKG-INFO
-SOURCES.txt
-top_level.txt

**Comment by gmelnik** [comment]
@koopertrooper Thanks for reporting this. The archive got corrupted on apps.splunk.com. It's now been rebuilt and re-uploaded.
