### ISSUE TITLE
"Multiple projects in a single Git repository" link incorrect

### ISSUE THREAD

**Issue by EcutDavid** [splunk/splunk-ref-pas-code#20]
Hi, there is a link to "Multiple projects in a single Git repository" in [Platform and tools: a kitbag for our journey](http://dev.splunk.com/view/dev-guide/SP-CAAAE2V)
![image](https://cloud.githubusercontent.com/assets/10692276/18472947/d4f48e2c-79ec-11e6-89fc-0a3b4752916b.png)

But the link is currently linking to http://dev.splunk.com/16107783.html , which is not exist anymore.

Should the link be nav to there(on the same page)?
![image](https://cloud.githubusercontent.com/assets/10692276/18473000/30b215d6-79ed-11e6-8d21-1ec90f02741a.png)

Thanks.

**Comment by tdhellmann** [comment]
Thanks for pointing those out! We'll get them fixed soon.

**Comment by tdhellmann** [comment]
We just pushed an update, this should be fixed.

**Comment by EcutDavid** [comment]
Cool, it works! Closing.
