### ISSUE TITLE
Suggestions for "Platform and tools: a kitbag for our journey" 

### ISSUE THREAD

**Issue by EcutDavid** [splunk/splunk-ref-pas-code#22]
"Don't forget to define the SPLUNK_HOME environment variable on your machine."  
![image](https://cloud.githubusercontent.com/assets/10692276/18498122/a13b1fae-7a66-11e6-908c-c3617351519b.png)
    
   
    
"Installing this version of the Splunk Event Generator is easy:"
![image](https://cloud.githubusercontent.com/assets/10692276/18498169/fdeb1380-7a66-11e6-8ec9-19a2d8daf4ea.png)

Not sure my suggestions is appropriative, thanks!

**Comment by tdhellmann** [comment]
Yep, you're right :) I'll get those changes made. 

I definitely appreciate these edits! As you go through the guidance, please don't hesitate to reach out to me with questions or suggestions like this.

**Comment by tdhellmann** [comment]
These changes are also live now. Thanks again!

**Comment by EcutDavid** [comment]
Thanks! It's updated, closing.
